# Generated by Django 2.2 on 2019-04-02 07:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kargo_api.User')),
                ('address', models.TextField()),
            ],
            bases=('kargo_api.user',),
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kargo_api.User')),
                ('rating', models.IntegerField(default=0)),
            ],
            bases=('kargo_api.user',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('shipment_date', models.DateField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('shipper_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kargo_api.Shipper')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('updated', models.DateTimeField(default=datetime.datetime.now)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kargo_api.Job')),
                ('transporter_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='kargo_api.Transporter')),
            ],
        ),
    ]
